// yoga/cues.js — what the teacher says about each pose. Pure content.
//
// ONE ENTRY PER POSE, and script.js turns it into three different spoken
// passages depending on the level. The fields are shaped by the teaching
// structure rather than by convenience:
//
//   spoken       how the name is said aloud ("pigeon pose", not "Pigeon")
//   enter        how to arrive in it — one sentence, movement only
//   cues         alignment, AUTHORED GROUND-UP and truncated by the level's
//                cue budget. So the first cue is the one a beginner gets, and it
//                had better be the foundational one. This ordering is the whole
//                reason a beginner and an expert can share a cue list.
//   easier       the way in. Every pose has one. Non-negotiable.
//   deeper       the way on. Advanced and expert only.
//   beginnerNote plain-language reassurance a beginner needs and nobody else
//   expertNote   the refinement only someone already in the shape can use
//   exit         a specific way out, where coming out badly is the risk
//
// WHY THE LEVELS SHARE A CUE LIST rather than having three separate paragraphs:
// a pose does not change meaning with experience. What changes is how much
// scaffolding you need and how much vocabulary you have. Writing three
// independent scripts would drift into three different poses.

export const POSE_CUES = {
  // ------------------------------------------------------------- breath / seat
  centering: {
    spoken: "a comfortable seat",
    enter: "Sit down, cross the shins, and rest the hands wherever they land.",
    cues: ["Let the sitting bones root down and the crown float up.",
      "Soften the jaw, the shoulders, the space between the eyebrows.",
      "Let the breath get slower than it wants to be."],
    easier: "If the low back rounds, sit up on a folded blanket or a cushion.",
    beginnerNote: "Nothing to achieve here. You're just arriving.",
  },
  ujjayi: {
    spoken: "ocean breath",
    enter: "Stay where you are and bring the attention to the throat.",
    cues: ["Breathe in through the nose, slow and full.",
      "Narrow the back of the throat slightly so the breath makes a soft sound.",
      "Match the length of the exhale to the inhale."],
    easier: "If the sound feels forced, drop it. Even nose breathing is the whole point.",
    deeper: "Let each breath get a little longer than the last, without strain.",
  },

  // -------------------------------------------------------------- restorative
  balasana_open: {
    spoken: "child's pose",
    enter: "Bring the knees wide, the big toes together, and sit the hips back toward the heels.",
    cues: ["Let the forehead rest down — on the mat, or on stacked fists.",
      "Walk the hands forward until the arms are long.",
      "Breathe into the back of the ribs and feel them widen."],
    easier: "A blanket behind the knees, or a bolster under the chest to rest on.",
    deeper: "Walk the hands over to one side for a stretch along the whole flank.",
    beginnerNote: "This is your rest position. Come back here any time you want it.",
  },
  viparita_karani: {
    spoken: "legs up the wall",
    enter: "Sit side-on to the wall, then swing the legs up as you lie down.",
    cues: ["Shuffle the hips as close to the wall as is comfortable.",
      "Let the arms fall open, palms up.",
      "Let the legs be completely passive — the wall is doing the work."],
    easier: "Move the hips further from the wall, or rest the calves on a chair seat.",
    beginnerNote: "This one asks nothing of you. That's the point of it.",
  },
  supported_bridge: {
    spoken: "supported bridge",
    enter: "Lie down, bend the knees, feet flat, then lift the hips and slide a block underneath.",
    cues: ["Put the block at its lowest height, under the bony part of the sacrum.",
      "Let the whole weight of the pelvis rest down onto it.",
      "Arms long by your sides, shoulders melting away from the ears."],
    easier: "A folded blanket instead of a block, or skip the prop and just rest.",
    exit: "Press into the feet, lift the hips, slide the block out, and lower down slowly.",
  },
  supported_fish: {
    spoken: "supported fish",
    enter: "Lie back over a bolster or rolled blanket placed along the length of the spine.",
    cues: ["Let the head rest fully — supported, never hanging.",
      "Open the arms wide and let the chest spread.",
      "Nothing to hold. Let gravity do all of it."],
    easier: "A lower prop, or a folded towel. The chest only needs to open a little.",
  },
  savasana: {
    spoken: "savasana",
    enter: "Lie all the way down and let the legs fall open.",
    cues: ["Let the floor take the full weight of you.",
      "Soften the face, the hands, the belly.",
      "Stop steering the breath — just let it happen."],
    easier: "A bolster under the knees, and something warm over you.",
  },

  // -------------------------------------------------------------------- seated
  cat_cow: {
    spoken: "cat and cow",
    enter: "Come to hands and knees, wrists under shoulders, knees under hips.",
    cues: ["Inhale, drop the belly and lift the chest forward.",
      "Exhale, round the back and let the head go heavy.",
      "Move at the speed of your own breath, not mine."],
    easier: "Come down onto the forearms if the wrists complain.",
    deeper: "Let the movement start in the tailbone and travel up one vertebra at a time.",
  },
  dandasana: {
    spoken: "staff pose",
    enter: "Sit up tall with both legs stretched out in front of you.",
    cues: ["Press the backs of the thighs down and flex the feet.",
      "Hands beside the hips, fingers pointing forward.",
      "Stack the shoulders over the hips and lift through the crown."],
    easier: "Sit up on a folded blanket and let the knees bend a little.",
    beginnerNote: "This is the seated version of standing tall. Harder than it looks.",
    deeper: "Press the hands down and lift the whole ribcage a little higher.",
  },
  virasana: {
    spoken: "hero pose",
    enter: "Kneel down, take the feet slightly wider than the hips, and sit back between them.",
    cues: ["Point the toes straight back, tops of the feet on the floor.",
      "Sit evenly on both sitting bones.",
      "Lift through the spine without gripping the belly."],
    easier: "Sit on a block placed between the feet. Or simply kneel normally.",
    beginnerNote: "If the knees have anything at all to say, come out. No exceptions.",
    deeper: "Stay longer here — the quads open on time, not on effort.",
  },
  padmasana: {
    spoken: "lotus",
    enter: "From a cross-legged seat, draw one foot high onto the opposite thigh, then the other.",
    cues: ["The opening comes from the hips, never from the knees.",
      "Let both knees settle toward the floor.",
      "Sit tall and rest the hands on the thighs."],
    easier: "Half lotus, or simple cross-legged. There's no prize for lotus.",
    beginnerNote: "If this isn't available today, cross-legged is the pose. Truly.",
    expertNote: "Let the knees be the last thing to arrive, never the first.",
  },
  ardha_padmasana: {
    spoken: "half lotus",
    enter: "Cross the shins, then lift one foot up onto the opposite thigh.",
    cues: ["Let the lifted knee travel toward the floor.",
      "Keep both sitting bones evenly weighted.",
      "Lengthen up through the spine."],
    easier: "Keep the foot on the calf rather than the thigh, or stay cross-legged.",
    deeper: "Draw the lifted foot a little higher onto the thigh.",
  },
  baddha_padmasana: {
    spoken: "bound lotus",
    enter: "From lotus, reach each hand behind the back and take hold of the opposite foot.",
    cues: ["Roll the shoulders back and down before you reach.",
      "Keep the chest open rather than collapsing forward.",
      "Breathe into the front of the body."],
    easier: "Cross-legged with the hands simply clasped behind the back.",
    expertNote: "Let the bind draw the collarbones wide rather than pulling the spine round.",
  },

  // -------------------------------------------------------------------- twists
  thread_needle: {
    spoken: "thread the needle",
    enter: "From hands and knees, slide the right arm underneath the left, palm up.",
    cues: ["Let the right shoulder and temple rest down on the mat.",
      "Keep the hips stacked high over the knees.",
      "Walk the top hand forward, or wrap it behind the low back."],
    easier: "Keep the top hand planted on the floor for support.",
    deeper: "Reach the top arm overhead along the floor for more through the shoulder.",
  },
  parivrtta_trikonasana: {
    spoken: "revolved triangle",
    enter: "From a short stance, square the hips forward and reach the opposite hand toward the front foot.",
    cues: ["Level the hips first — both hip points facing the front of the mat.",
      "Turn from the ribcage, not from the hips.",
      "Stack the top shoulder over the bottom one and reach up."],
    easier: "Hand to a block outside the front foot, and lift the back heel.",
    deeper: "Take the bottom hand to the outside edge of the front foot.",
    exit: "Look down, soften the front knee, and come up slowly.",
  },
  parivrtta_parsvakonasana: {
    spoken: "revolved side angle",
    enter: "From a lunge, bring the opposite elbow to the outside of the front thigh.",
    cues: ["Get the hips level before you rotate anything.",
      "Press the elbow into the thigh and the thigh back into the elbow.",
      "Draw the bottom shoulder away from the ear and open the chest up."],
    easier: "Back knee down, and hand to the floor instead of taking a bind.",
    deeper: "Reach the bottom hand under and the top hand behind to bind.",
  },
  parivrtta_anjaneyasana: {
    spoken: "revolved low lunge",
    enter: "From a low lunge with the back knee down, bring the hands to the heart.",
    cues: ["Square the hips toward the front of the mat.",
      "Hook the opposite elbow outside the front thigh.",
      "Press the palms together and open the top shoulder."],
    easier: "Keep both hands on the floor and just turn the chest.",
    deeper: "Open the top arm all the way to the sky and gaze past the fingers.",
  },
  ardha_matsyendrasana: {
    spoken: "half lord of the fishes",
    enter: "Sit tall, cross one foot over the opposite thigh, and plant it flat.",
    cues: ["Ground both sitting bones evenly before you turn.",
      "Lengthen up on the inhale, rotate a little more on the exhale.",
      "Let the head turn last, following the chest."],
    easier: "Keep the bottom leg straight, and place the back hand down for height.",
    deeper: "Hook the elbow outside the raised knee and take a gentle bind.",
  },
  bharadvajasana: {
    spoken: "Bharadvaja's twist",
    enter: "Sit with both legs folded to one side, then turn away from them.",
    cues: ["Sit evenly — a blanket under one hip if you're tipping.",
      "Lift through the spine, then rotate the ribs.",
      "Rest one hand behind you, the other on the opposite thigh."],
    easier: "Sit up on a folded blanket so both hips are level.",
    beginnerNote: "This is the gentlest twist there is. Nothing forced.",
    deeper: "Reach the back hand around for the opposite thigh.",
  },
  supta_matsyendrasana: {
    spoken: "a reclined twist",
    enter: "Lie on your back, draw the knees in, and let them fall to one side.",
    cues: ["Keep both shoulders heavy on the mat, even if the knees don't reach the floor.",
      "Open the opposite arm out wide.",
      "Breathe into the ribs on the top side."],
    easier: "A block or bolster between or under the knees so they have somewhere to land.",
    beginnerNote: "The shoulders staying down matters far more than the knees going down.",
    deeper: "Extend the top leg long and take hold of the foot.",
  },
  parivrtta_utkatasana: {
    spoken: "revolved chair",
    enter: "Sit down into chair pose, bring the palms together at the heart, then twist.",
    cues: ["Get both knees level with each other first.",
      "Hook the elbow to the outside of the opposite thigh.",
      "Press palm into palm and lift the chest away from the legs."],
    easier: "Stay higher in the legs, hands at the heart, and take half the twist.",
    deeper: "Open the arms — bottom hand down, top hand up.",
  },
  marichyasana_c: {
    spoken: "Marichyasana C",
    enter: "One leg long, the other knee up with the foot planted, then twist toward the raised knee.",
    cues: ["Ground the long leg and flex that foot.",
      "Lengthen the spine before rotating.",
      "Hook the opposite elbow outside the raised knee."],
    easier: "Elbow to the knee without the bind, or hold a strap behind the back.",
    deeper: "Wrap the arm around the shin and clasp the hands behind the back.",
  },
  marichyasana_d: {
    spoken: "Marichyasana D",
    enter: "Half lotus underneath, the other knee up, then twist toward the raised knee.",
    cues: ["Settle the lotus foot high on the thigh before anything turns.",
      "Sit tall and lengthen up through the crown.",
      "Twist from the ribs and reach around for the bind."],
    easier: "Take Marichyasana C instead — the folded leg is what makes this a knee pose.",
    expertNote: "The bind should follow the twist, never drag it.",
  },

  // ------------------------------------------------------------------ standing
  tadasana: {
    spoken: "mountain pose",
    enter: "Stand with the feet about hip-width and the arms relaxed by your sides.",
    cues: ["Spread the toes and feel all four corners of each foot.",
      "Let the tailbone drop and the ribs settle over the hips.",
      "Lift up through the crown and let the shoulders be heavy."],
    easier: "Take the feet a little wider if balance feels wobbly.",
    beginnerNote: "This is the reset. Everything standing comes back to this shape.",
    deeper: "Close the eyes and find the balance without a visual anchor.",
  },
  urdhva_hastasana: {
    spoken: "upward salute",
    enter: "From mountain, inhale and sweep both arms out and up overhead.",
    cues: ["Keep the front ribs knitted in rather than flaring.",
      "Reach up through the fingertips.",
      "Let the shoulders slide down away from the ears."],
    easier: "Take the arms shoulder-width apart instead of overhead.",
    deeper: "Take a gentle backbend, keeping the low ribs drawn in.",
  },
  utkatasana: {
    spoken: "chair pose",
    enter: "Feet together or hip-width, bend the knees and sit the hips back.",
    cues: ["Shift the weight into the heels — you should still see your toes.",
      "Draw the low ribs in so the low back doesn't arch.",
      "Reach the arms alongside the ears, or keep them at the heart."],
    easier: "Sit less deeply. Half the depth is still the pose.",
    deeper: "Sink until the thighs are closer to parallel, and hold there.",
  },
  high_lunge: {
    spoken: "high lunge",
    enter: "Step one foot back, keep the back heel lifted, and bend the front knee.",
    cues: ["Front knee stacked directly over the ankle.",
      "Press the back heel toward the wall behind you.",
      "Lift the arms up and lengthen the side body."],
    easier: "Shorten the stance and bring the hands to the hips.",
    deeper: "Sink the hips lower and draw the back thigh up strongly.",
  },
  virabhadrasana_1: {
    spoken: "warrior one",
    enter: "Step one foot back and turn it out to about forty-five degrees, then bend the front knee.",
    cues: ["Ground the outer edge of the back foot.",
      "Draw the back hip forward so both hips face the front.",
      "Reach the arms up and lift the chest."],
    easier: "Widen the feet side to side — squaring the hips is far easier with room.",
    deeper: "Deepen the front knee toward ninety degrees while keeping the back leg straight.",
  },
  virabhadrasana_2: {
    spoken: "warrior two",
    enter: "Wide stance, turn the front foot out and the back foot slightly in, then bend the front knee.",
    cues: ["Front heel lines up with the arch of the back foot.",
      "Track the front knee over the middle toes — don't let it fall inward.",
      "Open the arms wide and gaze softly past the front hand."],
    easier: "Bend the front knee less, and shorten the stance.",
    deeper: "Sink until the front thigh is closer to parallel with the floor.",
  },
  viparita_virabhadrasana: {
    spoken: "reverse warrior",
    enter: "From warrior two, turn the front palm up and reach that arm up and back.",
    cues: ["Keep the front knee bent and tracking over the toes.",
      "Rest the back hand lightly on the back leg — no weight on it.",
      "Lengthen both sides of the waist rather than crunching the bottom one."],
    easier: "Reach up rather than back. The side stretch is the point, not the bend.",
    deeper: "Deepen the front knee as the top arm reaches further back.",
  },
  utthita_parsvakonasana: {
    spoken: "extended side angle",
    enter: "From warrior two, bring the front forearm onto the front thigh.",
    cues: ["Keep the front knee tracking over the middle toes.",
      "Press the outer back foot down and lift the back inner thigh.",
      "Reach the top arm over the ear so the whole flank is long."],
    easier: "Forearm on the thigh rather than taking the hand to the floor.",
    deeper: "Take the bottom hand to a block or the floor outside the front foot.",
  },
  utthita_trikonasana: {
    spoken: "triangle",
    enter: "Wide stance, front foot turned out, both legs straight, then reach long over the front leg.",
    cues: ["Reach out first, and only then lower down.",
      "Keep both legs strong and lift the kneecaps.",
      "Stack the top shoulder over the bottom, and keep both waists long."],
    easier: "Hand to a block or the shin, and look forward instead of up.",
    deeper: "Take the hand to the floor outside the foot and open the chest further.",
  },
  utkata_konasana: {
    spoken: "goddess pose",
    enter: "Take a wide stance, turn the toes out, and bend both knees.",
    cues: ["Track the knees out over the middle toes.",
      "Drop the tailbone so the low back stays long.",
      "Bring the arms into a goal-post shape, or reach them up."],
    easier: "Sink only halfway. The legs will still know about it.",
    deeper: "Sink the hips toward knee height and hold there.",
  },

  // -------------------------------------------------------------- forward folds
  uttanasana: {
    spoken: "a standing forward fold",
    enter: "From standing, exhale and fold forward from the hips.",
    cues: ["Soften the knees generously — length matters more than straightness.",
      "Let the head and neck hang completely heavy.",
      "Shift the weight slightly forward into the balls of the feet."],
    easier: "Bend the knees deeply, or bring the hands onto blocks.",
    deeper: "Slowly straighten the legs while keeping the belly close to the thighs.",
    beginnerNote: "Touching your toes is not the goal and never was.",
  },
  ardha_uttanasana: {
    spoken: "a halfway lift",
    enter: "From the fold, inhale and lift the chest to flatten the back.",
    cues: ["Fingertips to the shins, the floor, or blocks.",
      "Draw the shoulders away from the ears.",
      "Reach the crown forward so the spine is one long line."],
    easier: "Hands on the thighs, and keep the knees bent.",
    deeper: "Fingertips to the floor with the legs fully straight.",
  },
  parsvottanasana: {
    spoken: "pyramid pose",
    enter: "Step one foot back, square the hips forward, and fold over the front leg.",
    cues: ["Get both hips level facing forward before folding.",
      "Keep a soft bend in the front knee.",
      "Lengthen the chest toward the front foot rather than rounding down."],
    easier: "Hands to blocks either side of the front foot.",
    deeper: "Clasp the hands behind the back as you fold.",
  },
  prasarita_a: {
    spoken: "a wide-legged forward fold",
    enter: "Step the feet wide and parallel, then hinge forward from the hips.",
    cues: ["Keep the outer edges of the feet grounded.",
      "Hands to the floor under the shoulders.",
      "Let the crown of the head drop toward the mat."],
    easier: "Hands to blocks, and keep a generous bend in the knees.",
    deeper: "Walk the hands back between the feet and let the head rest down.",
  },
  prasarita_c: {
    spoken: "wide-legged fold with a clasp",
    enter: "Feet wide, clasp the hands behind the back, then fold.",
    cues: ["Ground the feet and lift the kneecaps.",
      "Roll the shoulders back before you fold.",
      "Let the arms travel overhead only as far as they'll go."],
    easier: "Hold a strap between the hands instead of clasping.",
    deeper: "Let the clasped hands travel further overhead toward the floor.",
  },
  padangusthasana: {
    spoken: "big toe pose",
    enter: "Feet hip-width, fold forward and take hold of the big toes.",
    cues: ["Hook two fingers around each big toe.",
      "Inhale to lengthen the spine, exhale to fold deeper.",
      "Draw the elbows out wide."],
    easier: "Hold the ankles, or loop a strap under the feet.",
    deeper: "Straighten the legs completely and draw the chest to the shins.",
  },
  padahastasana: {
    spoken: "hand-under-foot pose",
    enter: "Fold forward and slide the palms under the soles of the feet.",
    cues: ["Toes to the wrist creases, palms up.",
      "Bend the knees as much as you need to get there.",
      "Let the weight shift slightly forward."],
    easier: "Hands to the shins instead — the wrists don't need this.",
    deeper: "Bend the elbows out and draw the crown toward the shins.",
  },
  paschimottanasana: {
    spoken: "a seated forward fold",
    enter: "Sit with the legs long and hinge forward from the hips.",
    cues: ["Flex the feet and press the thighs down.",
      "Lead with the chest rather than the head.",
      "Lengthen forward over the legs, not down toward them."],
    easier: "Loop a strap around the feet, bend the knees, and sit on a blanket.",
    deeper: "Take hold of the feet and draw the belly closer to the thighs.",
  },
  janu_sirsasana: {
    spoken: "head-to-knee pose",
    enter: "One leg long, the other sole to the inner thigh, then fold over the long leg.",
    cues: ["Turn the chest to face over the straight leg first.",
      "Keep the long leg's foot flexed and the thigh heavy.",
      "Fold from the hip, keeping the spine long."],
    easier: "A block under the bent knee, and a strap around the foot.",
    deeper: "Take hold of the foot and draw the forehead toward the shin.",
  },
  upavistha_konasana: {
    spoken: "a wide-legged seated fold",
    enter: "Open the legs wide, then walk the hands forward between them.",
    cues: ["Point the kneecaps up toward the ceiling.",
      "Sit up on the front of the sitting bones before folding.",
      "Walk forward only as far as the spine stays long."],
    easier: "Sit up on a blanket and stay completely upright. That is already the pose.",
    deeper: "Walk the hands further and let the chest come toward the floor.",
  },
  supta_padangusthasana: {
    spoken: "reclined hand-to-big-toe",
    enter: "Lie on your back and draw one leg up, holding the foot or a strap.",
    cues: ["Keep the bottom leg heavy and the hip on the floor.",
      "Flex both feet.",
      "Straighten the lifted leg only as far as the other hip stays down."],
    easier: "Bend the lifted knee, and bend the bottom knee with the foot flat.",
    beginnerNote: "A strap here is not cheating. Almost everyone uses one.",
    deeper: "Take the lifted leg out to the side, keeping the opposite hip down.",
  },
  kurmasana: {
    spoken: "tortoise pose",
    enter: "Sit with the legs wide, slide the arms under the knees, and lower the chest.",
    cues: ["Walk the heels forward and let the knees stay soft.",
      "Slide the arms out to the sides beneath the thighs.",
      "Let the chest and chin move toward the floor."],
    easier: "Take a wide-legged seated fold instead.",
    expertNote: "Let the shoulders travel under the legs before trying to straighten them.",
    deeper: "Straighten the legs and slide the arms further out to the sides.",
  },
  supta_kurmasana: {
    spoken: "sleeping tortoise",
    enter: "From tortoise, cross the ankles behind the head and bind the hands behind the back.",
    cues: ["Draw one leg high behind the shoulder before the other.",
      "Round the spine deliberately here.",
      "Breathe slowly — the chest has very little room."],
    easier: "Stay in tortoise. This one takes years, and that's completely fine.",
    expertNote: "If the breath shortens, come out. The bind is never worth the breath.",
  },
  yoga_mudra: {
    spoken: "yoga seal",
    enter: "From bound lotus, fold the chest forward toward the floor.",
    cues: ["Keep the bind and roll the shoulders back.",
      "Hinge from the hips rather than collapsing the chest.",
      "Let the crown release toward the mat."],
    easier: "Cross-legged, hands clasped behind, and fold gently forward.",
    expertNote: "Let the shoulders open behind you rather than the spine rounding further.",
  },
  caterpillar: {
    spoken: "caterpillar",
    enter: "Sit with the legs long and let the spine round as you fold forward.",
    cues: ["Let the knees soften — this one is meant to be passive.",
      "Let the head hang completely.",
      "Stop steering, and let gravity do all of it."],
    easier: "Rest the chest on a bolster laid across the thighs.",
    beginnerNote: "In yin we deliberately let the back round. Different rules here.",
    deeper: "Stay for a full five minutes and let the fascia do the work.",
  },
  prasarita_b: {
    spoken: "wide-legged fold, hands on hips",
    enter: "Feet wide, hands on the hips, then fold forward with a long spine.",
    cues: ["Draw the elbows toward each other behind you.",
      "Keep the legs strong and the kneecaps lifted.",
      "Hinge from the hip creases."],
    easier: "Hands to blocks in front of you instead.",
    deeper: "Draw the elbows together behind you as the crown lowers.",
  },
  prasarita_d: {
    spoken: "wide-legged fold with the big toes",
    enter: "Feet wide, fold, and take hold of the big toes.",
    cues: ["Hook two fingers around each big toe.",
      "Bend the elbows out to the sides.",
      "Draw the crown toward the floor."],
    easier: "Hold the ankles instead.",
    deeper: "Bend the elbows wide and bring the crown to the mat.",
  },
  ardha_baddha_padma_paschimottanasana: {
    spoken: "seated half-bound lotus fold",
    enter: "One foot into half lotus, reach behind for the foot, then fold over the long leg.",
    cues: ["Settle the lotus foot high on the opposite thigh first.",
      "Reach behind the back for the bind before folding.",
      "Fold over the straight leg with a long spine."],
    easier: "Head-to-knee pose without the bind.",
    expertNote: "If the knee objects at all, the hip isn't open yet. Take janu sirsasana.",
  },
  triang_mukha_eka_pada_paschimottanasana: {
    spoken: "three-limbed forward fold",
    enter: "Fold one shin back beside the hip, keep the other leg long, then fold forward.",
    cues: ["Sit evenly — the folded side wants to lift.",
      "Flex the long leg's foot and press the thigh down.",
      "Fold over the straight leg."],
    easier: "A blanket under the sitting bone on the folded side.",
    deeper: "Take hold of the foot and fold fully over the long leg.",
  },
  janu_sirsasana_b: {
    spoken: "head-to-knee B",
    enter: "Bend one knee and sit on that heel, other leg long, then fold.",
    cues: ["Position the heel under the perineum before sitting back.",
      "Turn the chest over the long leg.",
      "Fold forward with a long spine."],
    easier: "Head-to-knee A instead — the sitting-on-the-heel part is what makes this hard.",
    expertNote: "Let the heel find the perineum before you settle the weight down.",
  },
  janu_sirsasana_c: {
    spoken: "head-to-knee C",
    enter: "Ball of one foot down, heel toward the navel, other leg long, then fold.",
    cues: ["Set the foot carefully — the ankle and toes take real load.",
      "Keep the knee pointing out to the side.",
      "Fold over the long leg."],
    easier: "Head-to-knee A. C is hard on the knee and there is genuinely no rush.",
    expertNote: "Set the toes and the ball of the foot with real care — this is an ankle pose too.",
  },
  marichyasana_a: {
    spoken: "Marichyasana A",
    enter: "One leg long, the other knee up, wrap that arm around the shin and bind behind.",
    cues: ["Press the long leg down and flex that foot.",
      "Wrap the arm around the shin from the outside.",
      "Fold forward once the bind is set."],
    easier: "Hold a strap between the hands rather than clasping.",
    deeper: "Clasp the wrist behind the back and fold the chin toward the shin.",
  },
  marichyasana_b: {
    spoken: "Marichyasana B",
    enter: "Half lotus underneath, the other knee up, then bind and fold.",
    cues: ["Set the lotus foot high on the thigh first.",
      "Wrap around the raised shin and bind behind the back.",
      "Fold forward with the spine long."],
    easier: "Marichyasana A. The lotus leg is what makes this a knee pose.",
    expertNote: "The bind follows the fold; never fold to reach the bind.",
  },
  urdhva_mukha_paschimottanasana: {
    spoken: "upward forward fold",
    enter: "Balance on the sitting bones, take hold of the feet, and draw the legs and chest together.",
    cues: ["Find the balance point behind the sitting bones first.",
      "Straighten the legs only as far as the balance holds.",
      "Draw the chest toward the shins."],
    easier: "Boat pose — same balance, far less hamstring.",
    deeper: "Draw the chest all the way to the shins and hold the balance still.",
  },

  // -------------------------------------------------------------------- core
  phalakasana: {
    spoken: "plank",
    enter: "From hands and knees, step the feet back into one long line.",
    cues: ["Stack the shoulders directly over the wrists.",
      "Press the floor away so the upper back is broad.",
      "Draw the low ribs in and reach the heels back."],
    easier: "Drop the knees down, or come onto the forearms.",
    deeper: "Lift one foot a few inches without letting the hips twist.",
  },
  chaturanga: {
    spoken: "four-limbed staff pose",
    enter: "From plank, shift slightly forward and lower halfway with the elbows in.",
    cues: ["Shift forward first — the shoulders should pass over the fingertips.",
      "Hug the elbows in against the ribs.",
      "Stop when the elbows reach shoulder height."],
    easier: "Knees down, or lower all the way to the belly. Both are the pose.",
    beginnerNote: "Lowering with the knees down builds this far faster than dropping badly.",
    deeper: "Pause halfway down for a full breath before lowering or lifting.",
  },
  ashtanga_namaskara: {
    spoken: "knees, chest and chin",
    enter: "From plank with the knees down, lower the chest and chin to the mat.",
    cues: ["Knees down first, then the chest, then the chin.",
      "Keep the hips lifted and the elbows hugging in.",
      "Let the chest land between the hands."],
    easier: "This is already the gentler option. Take it any time.",
    deeper: "Lower with the knees lifted for a full chaturanga instead.",
  },
  navasana: {
    spoken: "boat pose",
    enter: "Sit down, lean back slightly, and lift the feet off the floor.",
    cues: ["Find the balance point just behind the sitting bones.",
      "Lift the chest and lengthen the spine before lifting the legs.",
      "Bring the shins parallel to the floor."],
    easier: "Hold behind the thighs and keep the toes lightly on the floor.",
    deeper: "Straighten the legs toward a V while keeping the chest lifted.",
  },
  vasisthasana: {
    spoken: "side plank",
    enter: "From plank, roll onto the outer edge of one foot and stack the hips.",
    cues: ["Set the bottom hand slightly forward of the shoulder.",
      "Press down through the bottom hand and lift the hips high.",
      "Stack the shoulders and reach the top arm up."],
    easier: "Bottom knee down, or come onto the forearm.",
    deeper: "Lift the top leg, or take hold of the big toe and extend it up.",
  },
  bakasana: {
    spoken: "crow pose",
    enter: "From a squat, plant the hands and bring the knees high onto the upper arms.",
    cues: ["Spread the fingers wide and grip the mat.",
      "Get the knees as high onto the arms as you can.",
      "Look forward, not down, and lean until the feet get light."],
    easier: "One foot at a time. Or stack a block under the feet to start higher.",
    beginnerNote: "Put a cushion in front of you and the fear mostly disappears.",
    exit: "Step the feet down one at a time, and rest in a squat.",
    deeper: "Straighten the arms and draw the heels toward the seat.",
  },
  bhujapidasana: {
    spoken: "shoulder pressing pose",
    enter: "From a squat, thread the arms behind the knees and plant the hands.",
    cues: ["Work the legs high onto the upper arms.",
      "Cross the ankles in front of you.",
      "Lean back slightly and lift the feet."],
    easier: "Stay in the squat with the hands planted.",
    expertNote: "The lift comes from rounding the back, not from strong arms.",
  },
  garbha_pindasana: {
    spoken: "embryo in the womb",
    enter: "From lotus, thread the arms through the gaps between calf and thigh.",
    cues: ["Settle into lotus first — this needs it.",
      "Work the arms through slowly; a little water on the skin helps.",
      "Hug in and find the round shape."],
    easier: "Simply hug the knees in and rock. Skip the lotus entirely.",
    expertNote: "Roll along the spine in a smooth circle, not in jerks.",
  },
  kukkutasana: {
    spoken: "rooster pose",
    enter: "From embryo, press the hands down and lift the whole seat off the mat.",
    cues: ["Plant the palms firmly beside the hips.",
      "Press down and draw the belly in.",
      "Lift, and keep the chest open."],
    easier: "Skip this one — it needs full lotus underneath it first.",
    expertNote: "Press the floor away rather than pulling up — the lift comes from the hands.",
  },
  tolasana: {
    spoken: "scales pose",
    enter: "In lotus, plant the hands beside the hips and press down to lift.",
    cues: ["Hands flat beside the hips, fingers forward.",
      "Draw the belly in and round slightly.",
      "Press down and lift the knees and seat clear of the floor."],
    easier: "Cross-legged, press the hands down, and let the hips stay put.",
    deeper: "Hold for ten full breaths without touching down.",
  },
  ubhaya_padangusthasana: {
    spoken: "both big toes pose",
    enter: "Roll up onto the sitting bones holding both big toes.",
    cues: ["Take hold of the toes before you roll up.",
      "Find the balance point, then straighten the legs.",
      "Lift the chest and look up."],
    easier: "Boat pose holding behind the thighs.",
    deeper: "Straighten the legs fully and lift the chest higher.",
  },

  // --------------------------------------------------------------- backbends
  urdhva_mukha: {
    spoken: "upward-facing dog",
    enter: "From lying face down, press into the hands and straighten the arms, lifting the thighs.",
    cues: ["Press the tops of the feet down firmly.",
      "Stack the shoulders over the wrists.",
      "Draw the chest forward through the arms and lift the thighs clear."],
    easier: "Take cobra instead — thighs stay down, and there's far less to hold up.",
    deeper: "Lift a little higher through the chest without crunching the low back.",
  },
  bhujangasana: {
    spoken: "cobra",
    enter: "Lie face down, hands under the shoulders, and lift the chest.",
    cues: ["Press the tops of the feet and the pubic bone down.",
      "Draw the elbows back toward the ribs.",
      "Lift with the back muscles first, and only then press with the hands."],
    easier: "Baby cobra — barely leave the floor. That's the whole pose.",
    deeper: "Straighten the arms further while keeping the shoulders down.",
    beginnerNote: "Low and strong beats high and floppy every single time.",
  },
  salamba_bhujangasana: {
    spoken: "sphinx pose",
    enter: "Lie face down and come up onto the forearms.",
    cues: ["Set the elbows directly under the shoulders.",
      "Press the forearms down and draw the chest forward.",
      "Let the legs and glutes stay soft."],
    easier: "Slide the elbows further forward to lower the whole shape.",
    deeper: "Walk the elbows in a little and lift the chest higher.",
  },
  salabhasana: {
    spoken: "locust pose",
    enter: "Lie face down, arms alongside the body, and lift everything.",
    cues: ["Reach the toes back before lifting them.",
      "Lift the chest, the arms and the legs together.",
      "Keep the gaze down at the mat so the neck stays long."],
    easier: "Lift only the upper body, or one leg at a time.",
    deeper: "Interlace the hands behind the back and lift higher.",
  },
  dhanurasana: {
    spoken: "bow pose",
    enter: "Lie face down, bend the knees, and take hold of the ankles.",
    cues: ["Take hold of the ankles, not the tops of the feet.",
      "Kick the shins into the hands — the kick does the lifting.",
      "Let the chest open as the thighs lift."],
    easier: "One side at a time, or a strap around the ankles.",
    exit: "Release the ankles slowly and rest one cheek on the mat.",
    deeper: "Kick more strongly and let the thighs lift clear of the mat.",
  },
  ustrasana: {
    spoken: "camel pose",
    enter: "Kneel with the hips over the knees and bring the hands to the low back.",
    cues: ["Keep the hips stacked directly over the knees the whole time.",
      "Lift the chest up and over before going back.",
      "Let the head go last, and only if the neck is happy."],
    easier: "Hands on the low back, or blocks beside the ankles. Keep the chin down.",
    deeper: "Reach back for the heels one hand at a time.",
    exit: "Bring the hands to the low back, lead with the chest, and come up slowly.",
  },
  setu_bandha: {
    spoken: "bridge pose",
    enter: "Lie down, bend the knees, feet flat and hip-width, then lift the hips.",
    cues: ["Walk the heels close enough to graze the fingertips.",
      "Press down through the feet and lift the hips.",
      "Roll the shoulders under and interlace the hands if you like."],
    easier: "Slide a block under the sacrum and simply rest there.",
    beginnerNote: "Once you're up, don't turn the head. The neck stays still.",
    exit: "Release the hands and roll the spine down one bone at a time.",
    deeper: "Interlace the hands beneath you and walk the shoulders further under.",
  },
  urdhva_dhanurasana: {
    spoken: "wheel pose",
    enter: "Lie down, feet flat, hands by the ears, then press up.",
    cues: ["Set the hands by the ears with the fingers pointing to the shoulders.",
      "Press the hips up first, then come onto the crown, then press all the way.",
      "Straighten the arms and let the head hang free."],
    easier: "Bridge instead. Or come onto the crown of the head and stop there.",
    exit: "Tuck the chin, lower slowly, and hug the knees in.",
    deeper: "Walk the hands and feet a little closer and lift the chest through.",
  },
  anahatasana: {
    spoken: "melting heart",
    enter: "From hands and knees, walk the hands forward and let the chest melt down.",
    cues: ["Keep the hips stacked high over the knees.",
      "Walk the hands as far forward as they'll go.",
      "Let the chest and the forehead release toward the mat."],
    easier: "A bolster under the chest, or come onto the forearms.",
    deeper: "Bring the chin to the mat instead of the forehead.",
  },
  matsyasana: {
    spoken: "fish pose",
    enter: "Lie down, slide the forearms under the hips, and lift the chest.",
    cues: ["Tuck the forearms and hands underneath the hips.",
      "Press down through the elbows to lift the chest high.",
      "Let the crown rest lightly down — the weight stays in the elbows."],
    easier: "A block lengthwise under the shoulder blades, and simply rest.",
    beginnerNote: "Almost no weight should be in the head. The elbows carry it.",
    deeper: "Lift the legs a few inches and reach through the toes.",
  },
  purvottanasana: {
    spoken: "upward plank",
    enter: "Sit with the legs long, hands behind you, and lift the hips.",
    cues: ["Set the hands behind the hips with the fingers pointing forward.",
      "Press down and lift the hips toward the ceiling.",
      "Point the toes and let the head release back if the neck is happy."],
    easier: "Reverse tabletop — knees bent, feet flat.",
    deeper: "Let the head release back and lift the hips higher.",
  },
  supta_virasana: {
    spoken: "reclined hero",
    enter: "From hero pose, walk back onto the elbows and then lower down.",
    cues: ["Check the knees are comfortable in hero before going back.",
      "Lower onto the elbows first and pause there.",
      "Keep the knees as close together as they'll stay."],
    easier: "Stay on the elbows, or lie back over a bolster.",
    exit: "Come up onto the elbows, then the hands, and straighten the legs slowly.",
    deeper: "Take the arms overhead and hold opposite elbows.",
  },
  uttana_padasana: {
    spoken: "extended leg pose",
    enter: "From fish pose, lift the legs and the arms to about forty-five degrees.",
    cues: ["Set the chest lift first.",
      "Lift both legs together, keeping them straight.",
      "Reach the arms alongside at the same angle."],
    easier: "Stay in supported fish with the legs down.",
    deeper: "Bring the palms together and reach the arms further past the head.",
  },
  seal: {
    spoken: "seal pose",
    enter: "From sphinx, walk the hands further forward and straighten the arms.",
    cues: ["Set the hands wider and further forward than in sphinx.",
      "Let the legs and the glutes stay completely soft.",
      "Let the low back compress gently — that's the intention here."],
    easier: "Stay on the forearms in sphinx.",
    beginnerNote: "In yin the back is meant to be passive. Different rules from a strong backbend.",
    deeper: "Walk the hands wider and let the chest open further.",
  },
  setu_bandhasana: {
    spoken: "the Ashtanga bridge",
    enter: "Lie down, bring the heels together, and press up onto the crown of the head.",
    cues: ["Set the feet together and the knees wide.",
      "Come onto the crown carefully — the neck carries load here.",
      "Lift the hips and press through the feet."],
    easier: "Ordinary bridge with the shoulders down. The neck version earns nothing extra.",
    exit: "Lower the hips first, then slide the head back down.",
    expertNote: "Take the weight in the feet and the arms; the crown only guides.",
  },

  // -------------------------------------------------------------- inversions
  adho_mukha: {
    spoken: "downward-facing dog",
    enter: "From hands and knees, tuck the toes and lift the hips up and back.",
    cues: ["Spread the fingers wide and press through the whole hand.",
      "Send the hips up and back — think of making an upside-down V.",
      "Bend the knees as much as you need to lengthen the spine."],
    easier: "Keep the knees generously bent, and let the heels stay lifted.",
    deeper: "Walk the heels toward the mat while keeping the spine long.",
    beginnerNote: "This is a back stretch first and a leg stretch second. Bend those knees.",
  },
  salamba_sarvangasana: {
    spoken: "shoulderstand",
    enter: "From lying down, lift the legs and hips up and support the back with the hands.",
    cues: ["Stack a folded blanket under the shoulders, head off the edge.",
      "Take the weight in the shoulders and elbows — never in the neck.",
      "Walk the hands up the back and lift the hips over the shoulders."],
    easier: "Legs up the wall instead. Most of the benefit, none of the neck load.",
    beginnerNote: "Once you're up, do not turn the head. Not once.",
    exit: "Lower the legs slowly overhead, then roll the spine down one bone at a time.",
    expertNote: "Keep walking the hands up the back — the higher they go, the lighter the neck.",
  },
  halasana: {
    spoken: "plough pose",
    enter: "From shoulderstand, lower the toes over the head toward the floor.",
    cues: ["Keep the hands supporting the back as you lower.",
      "Let the toes reach for the floor — they don't have to arrive.",
      "Keep the neck completely still."],
    easier: "Rest the feet on a chair behind you, or stay in bridge.",
    deeper: "Interlace the hands on the floor and roll the shoulders further under.",
  },
  karnapidasana: {
    spoken: "ear pressure pose",
    enter: "From plough, bend the knees down beside the ears.",
    cues: ["Lower the knees slowly toward the floor.",
      "Let the knees rest beside the ears if they reach.",
      "Keep breathing — the chest has very little room here."],
    easier: "Stay in plough, or come down entirely.",
    expertNote: "Let the knees find the floor before you draw them in beside the ears.",
  },
  sirsasana: {
    spoken: "headstand",
    enter: "Set the forearms down, interlace the fingers, and walk the feet in before lifting.",
    cues: ["Set the elbows shoulder-width — no wider.",
      "Press the forearms down hard; most of the weight lives there.",
      "Walk the feet in and lift with the core rather than kicking up."],
    easier: "Dolphin pose, or legs up the wall. Neither is a lesser pose.",
    beginnerNote: "Practise at a wall the first hundred times. Everyone does.",
    exit: "Lower one leg at a time with control, then rest in child's pose.",
    expertNote: "The legs should float up, not kick. If they kick, you are not ready to leave the wall.",
  },
  urdhva_padmasana: {
    spoken: "upward lotus",
    enter: "In shoulderstand, fold the legs into lotus and bring the hands to the knees.",
    cues: ["Establish a steady shoulderstand first.",
      "Fold one leg then the other into lotus.",
      "Press the hands into the knees and lift the thighs parallel."],
    easier: "Stay in shoulderstand with the legs straight.",
    expertNote: "Set the lotus before you look for the lift — never the other way round.",
  },
  pindasana: {
    spoken: "embryo pose",
    enter: "From upward lotus, lower the knees toward the forehead and wrap the arms around.",
    cues: ["Keep the elbows supporting until the legs are settled.",
      "Lower the knees toward the forehead.",
      "Wrap the arms around the shins and breathe into the back."],
    easier: "Knees toward the forehead without the lotus.",
    expertNote: "Keep breathing into the back body; the front has no room here.",
  },
  supta_konasana: {
    spoken: "reclined angle pose",
    enter: "From plough, take the legs wide and hold the big toes.",
    cues: ["Open the legs wide with the toes on the floor.",
      "Take hold of the big toes.",
      "Keep the weight in the shoulders, then roll up to sit."],
    easier: "Stay in a supported plough and skip the roll up.",
    expertNote: "Roll up with control and land with the legs still wide.",
  },

  // ------------------------------------------------------------- hip openers
  anjaneyasana: {
    spoken: "a low lunge",
    enter: "Step one foot forward and lower the back knee to the mat.",
    cues: ["Set the front knee directly over the ankle.",
      "Untuck the back toes and sink the hips forward.",
      "Lift the chest, and take the arms up if it feels good."],
    easier: "A folded blanket under the back knee, and hands on blocks either side.",
    deeper: "Sink the hips lower and reach the arms back into a gentle backbend.",
  },
  malasana: {
    spoken: "garland pose",
    enter: "Take the feet a little wider than the hips and squat down low.",
    cues: ["Turn the toes out slightly and sink the hips toward the floor.",
      "Bring the elbows inside the knees and press out gently.",
      "Lift the chest and lengthen the spine."],
    easier: "Sit on a block, and roll a blanket under the heels.",
    beginnerNote: "If the heels lift, that's completely normal. Put something under them.",
    deeper: "Bring the palms together and press the elbows out against the knees.",
  },
  baddha_konasana: {
    spoken: "bound angle pose",
    enter: "Sit down, bring the soles of the feet together, and let the knees fall open.",
    cues: ["Draw the heels in toward you, or let them travel away for a gentler version.",
      "Hold the feet or the ankles and sit up tall.",
      "Let the knees be heavy — never press them down."],
    easier: "Blocks under both knees, and take the feet further from the body.",
    deeper: "Fold forward from the hips, keeping the spine long.",
  },
  sucirandhrasana: {
    spoken: "figure four",
    enter: "Lie on your back, cross one ankle over the opposite knee.",
    cues: ["Flex the crossed foot to protect the knee.",
      "Thread the hands behind the bottom thigh.",
      "Draw the bottom leg in until you feel it in the outer hip."],
    easier: "Keep the bottom foot on the floor and just press the top knee away.",
    beginnerNote: "This gets you everything pigeon does, with none of the knee load.",
    deeper: "Draw the bottom knee closer in toward the chest.",
  },
  eka_pada_rajakapotasana: {
    spoken: "pigeon pose",
    enter: "From downward dog, bring one knee forward behind the wrist and stretch the other leg back.",
    cues: ["Angle the front shin — it does not have to be parallel.",
      "Get the hips square, and prop the folded-side hip if it's floating.",
      "Walk the hands forward and let the chest come down."],
    easier: "Reclined figure four instead — same hip, none of the knee load.",
    beginnerNote: "If the front knee has anything at all to say, come out. No negotiation.",
    exit: "Press into the hands, tuck the back toes, and step back to downward dog.",
    deeper: "Walk the front shin more parallel to the front of the mat.",
  },
  gomukhasana_legs: {
    spoken: "cow face legs",
    enter: "Cross one knee directly over the other and take the feet out to the sides.",
    cues: ["Stack the knees as close to one on top of the other as they'll go.",
      "Sit evenly on both sitting bones.",
      "Sit tall first, and only then think about folding."],
    easier: "Cross the shins loosely instead, and sit up on a block.",
    deeper: "Fold forward over the stacked knees with a long spine.",
  },
  agnistambhasana: {
    spoken: "fire log pose",
    enter: "Stack one shin directly on top of the other, both feet flexed.",
    cues: ["Flex both feet hard — that's what protects the knees.",
      "Stack the top shin over the bottom one.",
      "Sit tall, then fold forward only if the spine stays long."],
    easier: "Simple cross-legged, or a block under the top knee.",
    beginnerNote: "If the top knee is high in the air, that's just your hips. Support it.",
    deeper: "Fold forward over the stacked shins, keeping both feet flexed.",
  },
  ananda_balasana: {
    spoken: "happy baby",
    enter: "Lie on your back, draw the knees toward the armpits, and take hold of the outer feet.",
    cues: ["Keep the sacrum heavy on the mat.",
      "Take hold of the outer edges of the feet, or the ankles.",
      "Draw the knees down toward the floor beside the ribs."],
    easier: "One side at a time, or hold behind the thighs with a strap.",
    deeper: "Draw the knees wider and closer to the floor beside the ribs.",
  },
  dragon: {
    spoken: "dragon lunge",
    enter: "Step one foot forward into a deep low lunge and let the hips sink.",
    cues: ["Walk the front foot further forward than a normal lunge.",
      "Let the hips get heavy — this one is meant to be passive.",
      "Come down onto the forearms if that's available."],
    easier: "Hands on blocks, and a blanket under the back knee.",
    beginnerNote: "Yin holds are long. Find a version you could stay in for minutes.",
    deeper: "Come onto the forearms and let the hips sink lower still.",
  },
  sleeping_swan: {
    spoken: "sleeping swan",
    enter: "From pigeon, fold all the way forward over the front leg.",
    cues: ["Square the hips and support the folded-side hip if it lifts.",
      "Walk the hands forward and let the head rest down.",
      "Let everything soften — muscles off, gravity on."],
    easier: "Reclined figure four. Same hip, no knee load at all.",
    exit: "Walk the hands back, tuck the back toes, and come out slowly.",
    deeper: "Stay for a full five minutes and let the outer hip release on its own.",
  },
  shoelace: {
    spoken: "shoelace",
    enter: "Stack one knee over the other and fold gently forward.",
    cues: ["Stack the knees as best they'll stack.",
      "Sit up on a block if either hip is lifting.",
      "Fold forward slowly and let the spine round."],
    easier: "Cross the shins instead, and sit up on a block.",
    deeper: "Fold further forward and stay for a full five minutes.",
  },

  // ----------------------------------------------------------------- balance
  vrksasana: {
    spoken: "tree pose",
    enter: "Shift the weight into one foot and bring the other sole to the inner leg.",
    cues: ["Ground the standing foot and find a still point to gaze at.",
      "Place the sole on the calf or the inner thigh — never on the side of the knee.",
      "Press foot into leg and leg into foot, then take the arms where you like."],
    easier: "Toes stay on the floor with the heel to the ankle. A wall behind you helps.",
    beginnerNote: "Wobbling is not failing. It's the pose working.",
    deeper: "Bring the palms overhead, or close the eyes and find it without looking.",
  },
  garudasana: {
    spoken: "eagle pose",
    enter: "Bend the knees, cross one thigh over the other, then cross the arms.",
    cues: ["Sit down into the standing leg before you wrap.",
      "Cross the thighs, and hook the foot behind if it reaches.",
      "Cross the arms, bring the palms together, and lift the elbows."],
    easier: "Toe of the top foot down as a kickstand, and hands to opposite shoulders.",
    deeper: "Sink lower into the standing leg and lift the elbows to shoulder height.",
  },
  utthita_hasta_padangusthasana: {
    spoken: "extended hand-to-big-toe",
    enter: "Draw one knee up toward the chest and take hold of the foot or the shin.",
    cues: ["Ground the standing foot and lift the standing kneecap.",
      "Lift the knee high first, before trying to extend anything.",
      "Extend the leg only as far as the standing hip stays level."],
    easier: "A strap around the foot, or simply hold the knee up.",
    deeper: "Open the leg out to the side, keeping both hips level.",
  },
  virabhadrasana_3: {
    spoken: "warrior three",
    enter: "From a lunge, shift onto the front foot and lift the back leg parallel to the floor.",
    cues: ["Ground the standing foot and micro-bend that knee.",
      "Keep both hips level and facing the floor.",
      "Reach the crown forward and the back heel back, in equal measure."],
    easier: "Hands on blocks or a wall, and keep the back toes on the floor.",
    deeper: "Bring the arms alongside the ears and reach forward.",
  },
  ardha_chandrasana: {
    spoken: "half moon",
    enter: "From triangle, bend the front knee, step the back foot in, and lift it as you reach forward.",
    cues: ["Set the bottom hand about a foot ahead of the standing toes.",
      "Stack the top hip directly over the bottom one.",
      "Flex the lifted foot and reach it strongly back."],
    easier: "Bottom hand on a block, back to a wall, and gaze down.",
    deeper: "Open the chest fully and reach the top arm to the sky.",
  },
  natarajasana: {
    spoken: "dancer pose",
    enter: "Take hold of one foot behind you and reach the other arm forward.",
    cues: ["Ground the standing foot and find a still gaze point.",
      "Press the lifted foot into the hand — that's what lifts you.",
      "Reach the front arm forward as the chest lifts."],
    easier: "A strap around the lifted foot, and hold a wall with the free hand.",
    deeper: "Take the foot with both hands overhead and open the chest further.",
  },
  ardha_baddha_padmottanasana: {
    spoken: "standing half-bound lotus",
    enter: "Bring one foot into half lotus while standing, bind behind, and fold.",
    cues: ["Find the balance in half lotus before reaching for the bind.",
      "Reach behind the back and take hold of the lotus foot.",
      "Fold forward over the standing leg."],
    easier: "Tree pose and a forward fold, taken separately.",
    expertNote: "Find the bind standing tall before you fold a single degree.",
  },

  // ------------------------------------------------------------------ supine
  bananasana: {
    spoken: "banana pose",
    enter: "Lie on your back and walk the feet and shoulders over to one side.",
    cues: ["Keep the hips anchored in the centre of the mat.",
      "Walk both feet to one side and the shoulders the same way.",
      "Take hold of the top wrist if that feels good."],
    easier: "Less curve, and let the knees bend.",
    deeper: "Cross the top ankle over the bottom one for more through the side.",
  },
};

export const CUED_POSES = Object.keys(POSE_CUES);
